display:
  background:
    path: /usr/share/thermalright-lcd-control/themes/backgrounds/y010.png
    type: image
  date:
    color: '#FFFFFFFF'
    enabled: false
    font_size: 27
    position:
      x: 15
      y: 3
    text: ''
  foreground:
    alpha: 1.0
    enabled: true
    path: /usr/share/thermalright-lcd-control/themes/foregrounds/{resolution}/006b.png
    position:
      x: 0
      y: 0
  metrics:
    configs:
      - color: '#FFFFFFFF'
        enabled: true
        font_size: 27
        format_string: '{label}{value}{unit}'
        label: ''
        name: cpu_temperature
        position:
          x: 92
          y: 223
        unit: °
      - color: '#FFFFFFFF'
        enabled: true
        font_size: 27
        format_string: '{label}{value}{unit}'
        label: ''
        name: gpu_temperature
        position:
          x: 396
          y: 218
        unit: °
      - color: '#FFFFFFFF'
        enabled: true
        font_size: 27
        format_string: '{label}{value}{unit}'
        label: ''
        name: cpu_frequency
        position:
          x: 163
          y: 113
        unit: MHZ
      - color: '#FFFFFFFF'
        enabled: true
        font_size: 27
        format_string: '{label}{value}{unit}'
        label: ''
        name: gpu_frequency
        position:
          x: 175
          y: 322
        unit: MHZ
    enabled: true
  time:
    color: '#FFFFFFFF'
    enabled: true
    font_size: 27
    position:
      x: 243
      y: 221
    text: ''
